name: Build Go Executable

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.8'

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y \
            pkg-config \
            libgl1-mesa-dev \
            xorg-dev

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install Go modules
      run: go mod download

    - name: Build executable
      run: GOOS=linux GOARCH=amd64 go build -o PushClient

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: PushClient
        path: PushClient
