name: Build Go Executable

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: choco install mingw

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install Go modules
      run: go mod download

    - name: Build executable
      run: |
        set CGO_ENABLED=1
        set GOOS=windows
        set GOARCH=amd64
        go build -o myapp.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: myapp
        path: myapp.exe
