name: Generate release assets

on:
  release:
    types: [published]

env:
  CGO_ENABLED: 0

permissions:
  contents: write

jobs:
  releases-matrix:
    name: Release precompiled binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1.51
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "1.21"
          sha256sum: true